
# 개인 영역

server.port=8080

spring.datasource.hikari.username=postgres.nxtiwhgkbuykyiagnerc
spring.datasource.hikari.password=3j$pzCf$4$&ijT,
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# 파일 저장할 때 사용하는 경로
app.upload.base=/Users/guyeongju/upload/
# 저장된 파일을 가져올 때 사용하는 경로
app.upload.path=file:/Users/guyeongju/upload/