spring.application.name=SNS

spring.profiles.include=dev

server.port=80

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp




mybatis.type-aliases-package=com.sns.app
mybatis.configuration.map-underscore-to-camel-case=true

# test 또는 대량을 INSERT 시 cash 충돌 해결
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# ------ file 관리 설정
# multipart 사용 여부
spring.servlet.multipart.enabled=true
# 파일 하나당 최대 크기 설정 제한
spring.servlet.multipart.max-file-size=10MB
# 총 파일의 최대 크기 설정 제한
spring.servlet.multipart.max-request-size=100MB


# ---- file 저장 관리


# ---- file 위치를 연결할 가상의 url
app.upload.url=/files/**

app.member=member

#### AOP 사용 시
#### 부모가 없는 class 사용 시 에러 발생 방지
spring.aop.proxy-target-class=true


#### 메세지 설정
spring.messages.basename=messages/message
spring.messages.encoding=UTF-8
# 코드가 없을 때 에러 발생 여부
# true : 예외를 발생시키지 않고 key를 출력
# false : 예외를 발생
spring.messages.use-code-as-default-message=true


spring.messages.cache-duration=600